# Set update schedule for GitHub Actions
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Combine MSAL packages to one Pull Request.
      msal-dependencies:
        patterns:
          - "Microsoft.Identity.*"
    ignore:
      - dependency-name: "Microsoft.Office.Lasso"
