# Set update schedule for GitHub Actions
version: 2
registries:
  public-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
    groups:
      # Combine MSAL packages to one Pull Request.
      msal-dependencies:
        patterns:
          - "Microsoft.Identity.*"
    ignore:
      - dependency-name: "Microsoft.Office.Lasso"
