# Set update schedule for GitHub Actions
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/"
    registries:
      - nuget-azure-devops # Allow version updates for dependencies in this registry
    schedule:
      interval: "weekly"
    allow:
      # Allow updates for Lasso
      - dependency-name: "Microsoft.Office.Lasso"
      # Allow updates for MSAL and any packages starting "Microsoft.Identity"
      - dependency-name: "Microsoft.Identity*"

registries:
  nuget-azure-devops:
    type: nuget-feed
    url: https://office.pkgs.visualstudio.com/DefaultCollection/_packaging/Office/nuget/v3/index.json
    username: office
    password: ${{ secrets.ADO_TOKEN }}
