# This pipeline will be triggered when either main branch is pushed or 2AM on workdays.
variables:
  - name: tags
    value: "production"
    readonly: true

trigger:
  branches:
    include:
    - main
  batch: true

schedules:
- cron: 0 2 * * 1-5
  branches:
    include:
    - main

resources:
  repositories:
  - repository: CustomPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/OfficePipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: ubuntu-latest
      os: linux
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-latest
        os: windows
      # This prevents auto-injected Roslyn task from running the build again.
      roslyn:
        copyLogsOnly: true
    stages:
    - template: BuildAndTest.yml