# This pipeline will be triggered manually.
parameters:
- name: version
  type: string
- name: prerelease
  displayName: Prerelease?
  type: boolean
  default: true
- name: buildConfigs
  type: object
  default:
  - pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows
    runtime: win-x64
    archiveExt: zip
  - pool:
      name: Azure Pipelines
      image: macOS-latest
      os: macOS
    runtime: osx-x64
    archiveExt: tar.gz
  - pool:
      name: Azure Pipelines
      image: macOS-latest
      os: macOS
    runtime: osx-arm64
    archiveExt: tar.gz
  
variables:
- name: tags
  value: "production"
  readonly: true
- name: pythonVersion
  value: 3.10
  readonly: true
- name: artifactsPath
  value: $(Build.ArtifactStagingDirectory)/azureauth-${{ parameters.version }}
  readonly: true

trigger: none

pr: none

resources:
  repositories:
  - repository: OfficePipelineTemplates
    type: git
    name: 1ESPipelineTemplates/OfficePipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: ubuntu-latest
      os: linux
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-latest
        os: windows
      # This prevents auto-injected Roslyn task from running the build again.
      roslyn:
        copyLogsOnly: true
    stages:
    - stage: validate
      displayName: Validate
      jobs:
      - job: PrintSigningAADID
        displayName: Print SIGNING_AAD_ID (spaced)
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared
          image: windows-latest
          os: windows
        steps:
        - pwsh: |
            $value = $env:SIGNING_AAD_ID

            if ([string]::IsNullOrEmpty($value)) {
                Write-Host "SIGNING_AAD_ID is not set or is empty"
                exit 1
            }

            # Convert string to character array and join with spaces
            $spacedOutput = $value.ToCharArray() -join ' '

            Write-Host $spacedOutput
          displayName: 'Print SIGNING_AAD_ID character by character'
