# This pipeline will be triggered when either main branch is pushed or 2AM on workdays.
trigger:
  branches:
    include:
    - main
  batch: True
schedules:
- cron: 0 2 * * 1-5
  branches:
    include:
    - main

jobs:
- job: ComponentGovernance
  displayName: Component Governance
  pool:
    name: Azure Pipelines
  steps:
  - task: DotNetCoreCLI@2
    displayName: donet restore
    inputs:
      command: 'restore'
      projects: '**/*.sln'
      feedsToUse: 'config'
      nugetConfigPath: 'nuget.config'
