# This pipeline will be triggered when either main branch is pushed or 2AM on workdays.
trigger:
  branches:
    include:
    - main
  batch: True
schedules:
- cron: 0 2 * * 1-5
  branches:
    include:
    - main

jobs:
- job: ComponentGovernance
  pool:
    name: Azure Pipelines
  steps:
  - task: DotNetCoreInstaller@2
    displayName: Use .NET Core sdk 6.x
    inputs:
      version: 6.x

  - task: NuGetToolInstaller@0
    displayName: Use NuGet 6.x
    inputs:
      versionSpec: 6.x

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: '**/*.csproj'
      feedsToUse: 'config'
      nugetConfigPath: 'nuget.config'

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
    inputs:
      verbosity: Normal

