name: Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Get Azure DevOps Access Token
        id: getToken
        uses: "./.github/actions/get-ado-token"
        with:
          client-id: ${{ secrets.AZURE_RELEASE_WORKFLOW_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_RELEASE_WORKFLOW_TENANT_ID }}
          organization: ${{ secrets.ADO_ORGANIZATION }}

      - name: Restore dependencies
        run: dotnet restore
        env:
          ADO_TOKEN: ${{ steps.getToken.outputs.token }}

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Azure DevOps Access Token
      id: getToken
      uses: "./.github/actions/get-ado-token"
      with:
        client-id: ${{ secrets.AZURE_RELEASE_WORKFLOW_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_RELEASE_WORKFLOW_TENANT_ID }}
        organization: ${{ secrets.ADO_ORGANIZATION }}

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: csharp

    # Autobuild attempts to build any compiled languages  (C/C++, C#, Go, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
      env:
        ADO_TOKEN: ${{ steps.getToken.outputs.token }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:csharp"
