name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      # We use SemVer, anything before v1.0.0 is a pre-release, but this could also include versions like v1.1.0-beta.
      prerelease:
        description: 'Prerelease'
        required: true
        default: true
        type: boolean

jobs:
  # Special request from @kyle-rader and @goagain, so no one can create an invalid release.
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Validate version
      run: echo ${{ github.event.inputs.version }} | python ./bin/version.py

  build:
    runs-on: ${{ matrix.os }}
    needs: [validate]
    strategy:
      matrix:
        # We build on Linux, but don't yet ship Linux because we can't easily sign those releases.
        runtime: [linux-x64, osx-x64, osx-arm64, win10-x64]
        include:
          - runtime: linux-x64
            os: ubuntu-latest
          - runtime: osx-x64
            os: macos-latest
          - runtime: osx-arm64
            os: macos-latest
          - runtime: win10-x64
            os: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://office.pkgs.visualstudio.com/DefaultCollection/_packaging/Office/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.ADO_TOKEN }}
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        source-url: https://office.pkgs.visualstudio.com/DefaultCollection/_packaging/Office/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.ADO_TOKEN }}
    - name: Install dependencies
      run: dotnet restore --runtime ${{ matrix.runtime }}
    - name: Test
      run: dotnet test --no-restore --configuration release
    - name: Build artifacts
      run: dotnet publish src/AzureAuth/AzureAuth.csproj --configuration release --self-contained true --runtime ${{ matrix.runtime }} --output dist/${{ matrix.runtime }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: azureauth-${{ github.event.inputs.version }}-${{ matrix.runtime }}
        path: dist/${{ matrix.runtime }}

  sign:
    # This step has to run on Windows because ESRPClient.exe is currently only available for that platform.
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - name: Download ESRPClient.exe
        env:
          ESRP_VERSION: ${{ secrets.ESRP_VERSION }}
          NUGET_CREDENTIALS: ${{ secrets.NUGET_CREDENTIALS }}
        run: |
          nuget sources add -Name esrp -Username esrp-downloader -Password $env:NUGET_CREDENTIALS -Source https://microsoft.pkgs.visualstudio.com/_packaging/ESRP/nuget/v3/index.json
          nuget install Microsoft.EsrpClient -Version "$env:ESRP_VERSION" -OutputDirectory .\esrp -Source https://microsoft.pkgs.visualstudio.com/_packaging/ESRP/nuget/v3/index.json
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # We need these certificates installed so that we can run ESRPClient.exe.
      - name: Install certificates
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
          AZURE_VAULT: ${{ secrets.AZURE_VAULT }}
          ESRP_AAD_CERT_NAME: ${{ secrets.AZURE_VAULT_ESRP_AAD_CERT_NAME }}
          ESRP_AAD_CERT_VERSION: ${{ secrets.AZURE_VAULT_ESRP_AAD_CERT_VERSION }}
          ESRP_REQ_CERT_NAME: ${{ secrets.AZURE_VAULT_ESRP_REQ_CERT_NAME }}
          ESRP_REQ_CERT_VERSION: ${{ secrets.AZURE_VAULT_ESRP_REQ_CERT_VERSION }}
        run: |
          az keyvault secret download --subscription "$env:AZURE_SUBSCRIPTION" --vault-name "$env:AZURE_VAULT" --name "$env:ESRP_AAD_CERT_NAME" --version "$env:ESRP_AAD_CERT_VERSION" -f cert.pfx
          certutil -f -importpfx cert.pfx
          Remove-Item cert.pfx

          az keyvault secret download --subscription "$env:AZURE_SUBSCRIPTION" --vault-name "$env:AZURE_VAULT" --name "$env:ESRP_REQ_CERT_NAME" --version "$env:ESRP_REQ_CERT_VERSION" -f cert.pfx
          certutil -f -importpfx cert.pfx
          Remove-Item cert.pfx
      # We download all artifacts and overwrite them with signed files, but only upload ones which we can properly sign.
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Sign artifacts
        env:
          SIGNING_AAD_ID: ${{ secrets.SIGNING_AAD_ID }}
          SIGNING_TENANT_ID: ${{ secrets.SIGNING_TENANT_ID }}
          SIGNING_KEY_CODE_AUTHENTICODE: ${{ secrets.SIGNING_KEY_CODE_AUTHENTICODE }}
          SIGNING_KEY_CODE_MAC: ${{ secrets.SIGNING_KEY_CODE_MAC }}
          SIGNING_CUSTOMER_CORRELATION_ID: ${{ secrets.SIGNING_CUSTOMER_CORRELATION_ID }}
          ESRP_CLIENT_EXE: ".\\esrp\\Microsoft.EsrpClient.${{ secrets.ESRP_VERSION }}\\tools\\EsrpClient.exe"
        # We might be able to speed/clean up this job by using another matrix strategy.
        run: |
          python .\bin\sign.py "$env:ESRP_CLIENT_EXE" --runtime=win10-x64 --source=azureauth-${{ github.event.inputs.version }}-win10-x64
          python .\bin\sign.py "$env:ESRP_CLIENT_EXE" --runtime=osx-x64 --source=azureauth-${{ github.event.inputs.version }}-osx-x64
          python .\bin\sign.py "$env:ESRP_CLIENT_EXE" --runtime=osx-arm64 --source=azureauth-${{ github.event.inputs.version }}-osx-arm64
      - name: Upload signed win10-x64 artifacts
        uses: actions/upload-artifact@v3
        with:
          name: azureauth-${{ github.event.inputs.version }}-win10-x64
          path: azureauth-${{ github.event.inputs.version }}-win10-x64
      - name: Upload signed osx-x64 artifacts
        uses: actions/upload-artifact@v3
        with:
          name: azureauth-${{ github.event.inputs.version }}-osx-x64
          path: azureauth-${{ github.event.inputs.version }}-osx-x64
      - name: Upload signed osx-arm64 artifacts
        uses: actions/upload-artifact@v3
        with:
          name: azureauth-${{ github.event.inputs.version }}-osx-arm64
          path: azureauth-${{ github.event.inputs.version }}-osx-arm64

  # Currently we package artifacts into the most commonly accessible archive format for their respective platforms.
  package:
    runs-on: ubuntu-latest
    needs: [sign]
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    - name: Install Zip
      run: sudo apt install -y zip
    - name: Create win10-x64 archive
      run: |
        cd azureauth-${{ github.event.inputs.version }}-win10-x64
        zip ../azureauth-${{ github.event.inputs.version }}-win10-x64.zip *
    - name: Upload win10-x64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: azureauth-${{ github.event.inputs.version }}-win10-x64.zip
        path: azureauth-${{ github.event.inputs.version }}-win10-x64.zip
    - name: Create osx-x64 archive
      run: |
        cd azureauth-${{ github.event.inputs.version }}-osx-x64
        tar -czf ../azureauth-${{ github.event.inputs.version }}-osx-x64.tar.gz *
    - name: Upload osx-x64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: azureauth-${{ github.event.inputs.version }}-osx-x64.tar.gz
        path: azureauth-${{ github.event.inputs.version }}-osx-x64.tar.gz
    - name: Create osx-arm64 archive
      run: |
        cd azureauth-${{ github.event.inputs.version }}-osx-arm64
        tar -czf ../azureauth-${{ github.event.inputs.version }}-osx-arm64.tar.gz *
    - name: Upload osx-arm64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: azureauth-${{ github.event.inputs.version }}-osx-arm64.tar.gz
        path: azureauth-${{ github.event.inputs.version }}-osx-arm64.tar.gz
    
  release:
    runs-on: ubuntu-latest
    needs: [package]
    # The 'release' environment is what requires reviews before creating the release.
    environment:
      name: release
    # These permissions are required in order to use `softprops/action-gh-release` to upload.
    permissions:
      contents: write
    steps:
    - name: Download win10-x64 artifact
      uses: actions/download-artifact@v3
      with:
        name: azureauth-${{ github.event.inputs.version }}-win10-x64.zip
    - name: Download osx-x64 artifact
      uses: actions/download-artifact@v3
      with:
        name: azureauth-${{ github.event.inputs.version }}-osx-x64.tar.gz
    - name: Download osx-arm64 artifact
      uses: actions/download-artifact@v3
      with:
        name: azureauth-${{ github.event.inputs.version }}-osx-arm64.tar.gz
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.inputs.version }}
        body: "Release ${{ github.event.inputs.version }}. See [`CHANGELOG.md`](https://github.com/AzureAD/microsoft-authentication-cli/blob/${{ github.event.inputs.version }}/CHANGELOG.md) for updates."
        tag_name: ${{ github.event.inputs.version }}
        prerelease: ${{ github.event.inputs.prerelease }}
        files: |
          azureauth-${{ github.event.inputs.version }}-win10-x64.zip
          azureauth-${{ github.event.inputs.version }}-osx-x64.tar.gz
          azureauth-${{ github.event.inputs.version }}-osx-arm64.tar.gz
